# Generated by Django 5.2.12 on 2026-04-07 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CauHinhGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_truc', models.IntegerField(choices=[(0, 'Ăn'), (1, 'Ngủ')], verbose_name='Loại trực')),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Đơn giá')),
                ('ngay_ap_dung', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày áp dụng')),
            ],
            options={
                'verbose_name': 'Cấu hình giá',
                'verbose_name_plural': '2. Cấu hình giá',
                'unique_together': {('loai_truc', 'ngay_ap_dung')},
            },
        ),
    ]
