# Generated by Django 5.2.12 on 2026-04-17 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cauhinhgia',
            name='nguoi_cap_nhat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cauhinh_da_sua', to=settings.AUTH_USER_MODEL, verbose_name='Người chỉnh sửa'),
        ),
    ]
