# Generated by Django 5.2.12 on 2026-04-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cauhinhgia_nguoi_cap_nhat'),
    ]

    operations = [
        migrations.CreateModel(
            name='CauHinhHeThong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam_hoc', models.CharField(default='2025-2026', max_length=20, verbose_name='Năm học')),
                ('nguoi_phu_trach', models.CharField(default='Tạ Thị Diệu Lê', max_length=100, verbose_name='Người phụ trách bán trú')),
                ('ten_truong', models.CharField(default='LÊ THỊ HỒNG GẤM', max_length=200, verbose_name='Tên trường/trung tâm')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình hệ thống',
                'verbose_name_plural': '1. Cấu hình hệ thống',
            },
        ),
    ]
