# Generated by Django 5.2.12 on 2026-04-07 16:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quanli', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiemDanhHS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày')),
                ('diem_danh_an', models.IntegerField(choices=[(0, 'Có mặt'), (1, 'Vắng'), (2, 'Phép')], default=0, verbose_name='Điểm danh ăn')),
                ('diem_danh_ngu', models.IntegerField(choices=[(0, 'Có mặt'), (1, 'Vắng'), (2, 'Phép')], default=0, verbose_name='Điểm danh ngủ')),
                ('ghi_chu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú')),
                ('ma_hs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanli.hocsinh', verbose_name='Học sinh')),
            ],
            options={
                'verbose_name': 'Điểm danh',
                'verbose_name_plural': '5. Điểm danh học sinh',
                'indexes': [models.Index(fields=['ngay'], name='nghiepvu_di_ngay_37d760_idx')],
                'constraints': [models.UniqueConstraint(fields=('ma_hs', 'ngay'), name='UQ_DiemDanh_Ngay')],
            },
        ),
        migrations.CreateModel(
            name='PhanCongTrucGV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField(verbose_name='Ngày trực')),
                ('loai_truc', models.IntegerField(choices=[(0, 'Ăn'), (1, 'Ngủ')], verbose_name='Loại ca')),
                ('xac_nhan_truc', models.BooleanField(default=True, verbose_name='Xác nhận trực')),
                ('ma_gv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_phan_cong', to='quanli.giaovien', verbose_name='GV phân công')),
                ('ma_gv_truc_thay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ds_truc_thay', to='quanli.giaovien', verbose_name='GV trực thay')),
                ('ma_phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanli.phong', verbose_name='Phòng')),
            ],
            options={
                'verbose_name': 'Phân công',
                'verbose_name_plural': '6. Phân công trực GV',
                'constraints': [models.UniqueConstraint(fields=('ma_gv', 'ngay', 'loai_truc'), name='UQ_Lich_Ca_Nhan_GV'), models.CheckConstraint(condition=models.Q(('ma_gv', models.F('ma_gv_truc_thay')), _negated=True), name='CK_Khong_Tu_Thay')],
            },
        ),
    ]
