# Generated by Django 5.2.12 on 2026-04-11 15:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nghiepvu', '0001_initial'),
        ('quanli', '0004_alter_phong_ma_phong'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiemDanhPhong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField(default=django.utils.timezone.now)),
                ('loai_truc', models.IntegerField(choices=[(0, 'Ăn'), (1, 'Ngủ')])),
                ('da_diem_danh', models.BooleanField(default=False)),
                ('thoi_gian', models.DateTimeField(auto_now=True)),
                ('ma_phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_diem_danh', to='quanli.phong')),
            ],
            options={
                'verbose_name': 'Điểm danh phòng',
                'verbose_name_plural': 'Điểm danh theo phòng',
                'constraints': [models.UniqueConstraint(fields=('ma_phong', 'ngay', 'loai_truc'), name='UQ_Phong_Ngay_Loai')],
            },
        ),
    ]
