# Generated by Django 5.2.12 on 2026-04-15 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nghiepvu', '0002_diemdanhphong'),
        ('quanli', '0008_phong_sl_diem_danh_phong_sl_ho_tro'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichTrucCoDinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thu', models.IntegerField(choices=[(0, 'Thứ 2'), (1, 'Thứ 3'), (2, 'Thứ 4'), (3, 'Thứ 5'), (4, 'Thứ 6')], verbose_name='Thứ trong tuần')),
                ('ma_gv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanli.giaovien', verbose_name='Giáo viên')),
                ('ma_phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanli.phong', verbose_name='Phòng')),
            ],
            options={
                'verbose_name': 'Lịch trực cố định',
                'verbose_name_plural': '7. Lịch trực khung',
                'constraints': [models.UniqueConstraint(fields=('ma_gv', 'thu'), name='UQ_LichCoDinh_GV_Thu')],
            },
        ),
    ]
