# Generated by Django 5.2.12 on 2026-04-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nghiepvu', '0003_lichtruccodinh'),
        ('quanli', '0009_giaovien_lich_ranh'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='phancongtrucgv',
            name='UQ_Lich_Ca_Nhan_GV',
        ),
        migrations.AddConstraint(
            model_name='phancongtrucgv',
            constraint=models.UniqueConstraint(fields=('ma_gv', 'ngay', 'loai_truc', 'ma_phong'), name='UQ_Lich_GV_Ngay_Loai_Phong'),
        ),
    ]
