# Generated by Django 5.2.12 on 2026-04-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nghiepvu', '0004_allow_dual_shift_gv'),
        ('quanli', '0009_giaovien_lich_ranh'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lichtruccodinh',
            name='UQ_LichCoDinh_GV_Thu',
        ),
        migrations.AddConstraint(
            model_name='lichtruccodinh',
            constraint=models.UniqueConstraint(fields=('ma_gv', 'thu', 'ma_phong'), name='UQ_LichCoDinh_GV_Thu_Phong'),
        ),
    ]
