# Generated by Django 5.2.12 on 2026-04-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffuser',
            options={'verbose_name': 'Người dùng', 'verbose_name_plural': 'Quản lý người dùng'},
        ),
        migrations.AddField(
            model_name='staffuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hoc_vu', 'Học vụ'), ('quan_ly', 'Quản lý'), ('ke_toan', 'Kế toán')], default='ke_toan', max_length=10, verbose_name='Vai trò'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='fullname',
            field=models.CharField(default='', max_length=100, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='position',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Chức vụ'),
        ),
    ]
