# Generated by Django 5.2.12 on 2026-04-07 16:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiaoVien',
            fields=[
                ('ma_gv', models.AutoField(primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('gioi_tinh', models.IntegerField(choices=[(0, 'Nam'), (1, 'Nữ')], verbose_name='Giới tính')),
                ('so_dien_thoai', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='SĐT')),
                ('dang_lam', models.BooleanField(default=True, verbose_name='Đang tham gia bán trú')),
            ],
            options={
                'verbose_name': 'Giáo viên',
                'verbose_name_plural': '3. Danh sách giáo viên',
            },
        ),
        migrations.CreateModel(
            name='CauHinhGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_truc', models.IntegerField(choices=[(0, 'Ăn'), (1, 'Ngủ')], verbose_name='Loại trực')),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Đơn giá')),
                ('ngay_ap_dung', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày áp dụng')),
            ],
            options={
                'verbose_name': 'Cấu hình giá',
                'verbose_name_plural': '2. Cấu hình giá',
                'unique_together': {('loai_truc', 'ngay_ap_dung')},
            },
        ),
        migrations.CreateModel(
            name='Phong',
            fields=[
                ('ma_phong', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Mã phòng')),
                ('loai_phong', models.IntegerField(choices=[(0, 'Ăn'), (1, 'Ngủ')], verbose_name='Loại phòng')),
                ('suc_chua', models.PositiveIntegerField(verbose_name='Sức chứa')),
                ('gioi_tinh', models.IntegerField(blank=True, choices=[(0, 'Nam'), (1, 'Nữ')], null=True, verbose_name='Giới tính (Phòng ngủ)')),
            ],
            options={
                'verbose_name': 'Phòng',
                'verbose_name_plural': '1. Danh sách phòng',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('gioi_tinh__isnull', True), ('loai_phong', 0)), models.Q(('gioi_tinh__isnull', False), ('loai_phong', 1)), _connector='OR'), name='CK_Phong_Loai_GT')],
            },
        ),
        migrations.CreateModel(
            name='HocSinh',
            fields=[
                ('ma_hs', models.AutoField(primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('gioi_tinh', models.IntegerField(choices=[(0, 'Nam'), (1, 'Nữ')], verbose_name='Giới tính')),
                ('lop', models.CharField(max_length=10, verbose_name='Lớp')),
                ('dang_hoc', models.BooleanField(default=True, verbose_name='Đang tham gia bán trú')),
                ('ma_phong_an', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hs_an', to='quanli.phong', verbose_name='Phòng ăn')),
                ('ma_phong_ngu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hs_ngu', to='quanli.phong', verbose_name='Phòng ngủ')),
            ],
            options={
                'verbose_name': 'Học sinh',
                'verbose_name_plural': '4. Danh sách học sinh',
            },
        ),
    ]
