# Generated by Django 5.2.12 on 2026-04-07 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quanli', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CauHinhGia',
        ),
    ]
