# Generated by Django 5.2.12 on 2026-04-11 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanli', '0002_delete_cauhinhgia'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuaVatDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam_hoc', models.CharField(max_length=10)),
                ('lan_mua', models.PositiveIntegerField(default=1)),
                ('loai_vat_dung', models.CharField(choices=[('CHIEU', 'Chiếu'), ('GOI', 'Gối'), ('VO_GOI', 'Vỏ gối')], max_length=10)),
                ('so_luong', models.PositiveIntegerField()),
                ('ngay_mua', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhanBoVatDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='phong',
            name='CK_Phong_Loai_GT',
        ),
        migrations.RemoveField(
            model_name='giaovien',
            name='ma_gv',
        ),
        migrations.RemoveField(
            model_name='hocsinh',
            name='ma_hs',
        ),
        migrations.AddField(
            model_name='giaovien',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='hocsinh',
            name='ghi_chu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hocsinh',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='giaovien',
            name='dang_lam',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='giaovien',
            name='gioi_tinh',
            field=models.IntegerField(choices=[(0, 'Nam'), (1, 'Nữ')]),
        ),
        migrations.AlterField(
            model_name='giaovien',
            name='ho_ten',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='giaovien',
            name='so_dien_thoai',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hocsinh',
            name='dang_hoc',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hocsinh',
            name='gioi_tinh',
            field=models.IntegerField(choices=[(0, 'Nam'), (1, 'Nữ')]),
        ),
        migrations.AlterField(
            model_name='hocsinh',
            name='ho_ten',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hocsinh',
            name='lop',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hocsinh',
            name='ma_phong_an',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hs_an', to='quanli.phong'),
        ),
        migrations.AlterField(
            model_name='hocsinh',
            name='ma_phong_ngu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hs_ngu', to='quanli.phong'),
        ),
        migrations.AlterField(
            model_name='phong',
            name='gioi_tinh',
            field=models.IntegerField(blank=True, choices=[(0, 'Nam'), (1, 'Nữ')], null=True),
        ),
        migrations.AlterField(
            model_name='phong',
            name='loai_phong',
            field=models.IntegerField(choices=[(0, 'Ăn'), (1, 'Ngủ')]),
        ),
        migrations.AlterField(
            model_name='phong',
            name='ma_phong',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='phong',
            name='suc_chua',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='phong',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('gioi_tinh__isnull', True), ('loai_phong', 0)), models.Q(('gioi_tinh__isnull', False), ('loai_phong', 1)), _connector='OR'), name='ck_phong_loai_gt'),
        ),
        migrations.AlterUniqueTogether(
            name='muavatdung',
            unique_together={('nam_hoc', 'lan_mua', 'loai_vat_dung')},
        ),
        migrations.AddField(
            model_name='phanbovatdung',
            name='mua',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phan_bo', to='quanli.muavatdung'),
        ),
        migrations.AddField(
            model_name='phanbovatdung',
            name='phong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanli.phong'),
        ),
        migrations.AlterUniqueTogether(
            name='phanbovatdung',
            unique_together={('mua', 'phong')},
        ),
    ]
