# Generated by Django 5.2.12 on 2026-04-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanli', '0003_muavatdung_phanbovatdung_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phong',
            name='ma_phong',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
