# Generated by Django 5.2.12 on 2026-04-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanli', '0004_alter_phong_ma_phong'),
    ]

    operations = [
        migrations.AddField(
            model_name='hocsinh',
            name='ma_ban_tru',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Mã bán trú'),
        ),
    ]
