# Generated by Django 5.2.12 on 2026-04-15 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quanli', '0005_add_ma_ban_tru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hocsinh',
            name='ma_ban_tru',
        ),
    ]
