# Generated by Django 5.2.12 on 2026-04-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanli', '0006_remove_ma_ban_tru'),
    ]

    operations = [
        migrations.AddField(
            model_name='giaovien',
            name='nhiem_vu',
            field=models.IntegerField(choices=[(0, 'Điểm danh'), (1, 'Hỗ trợ')], default=0),
        ),
    ]
