# Generated by Django 5.2.12 on 2026-04-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanli', '0007_giaovien_nhiem_vu'),
    ]

    operations = [
        migrations.AddField(
            model_name='phong',
            name='sl_diem_danh',
            field=models.IntegerField(default=1, verbose_name='Số lượng Điểm danh'),
        ),
        migrations.AddField(
            model_name='phong',
            name='sl_ho_tro',
            field=models.IntegerField(default=1, verbose_name='Số lượng Hỗ trợ'),
        ),
    ]
