# Generated by Django 5.2.12 on 2026-04-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanli', '0008_phong_sl_diem_danh_phong_sl_ho_tro'),
    ]

    operations = [
        migrations.AddField(
            model_name='giaovien',
            name='lich_ranh',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
